routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes([
    'register' => false
]);

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth']], function ()
{
    Route::get('/ajax/address-to-voters/{id}', 'App\Http\Controllers\AjaxController@addressToVoters');
    Route::get('/ajax/road-to-addresses/{id}', 'App\Http\Controllers\AjaxController@roadToAddresses');
    Route::get('/ajax/ward-to-roads/{id}', 'App\Http\Controllers\AjaxController@wardToRoads');

    Route::post('/activist/contact-delete', 'App\Http\Controllers\ActivistController@contactDelete')->name('activist.contact-delete');
    Route::post('/activist/upload', 'App\Http\Controllers\ActivistController@upload')->name('activist.upload');
    Route::get('/activist/{id}/export', 'App\Http\Controllers\ActivistController@export')->name('activist.export');
    Route::get('/activist/{id}', 'App\Http\Controllers\ActivistController@show')->name('activist.show');
    Route::post('/activist/{id}', 'App\Http\Controllers\ActivistController@showPost')->name('activist.show-post');
    Route::get('/activist', 'App\Http\Controllers\ActivistController@index')->name('activist.index');

    Route::get('/address/create', 'App\Http\Controllers\AddressController@create')->name('address.create');
    Route::post('/address/create', 'App\Http\Controllers\AddressController@createPost')->name('address.create-post');
    Route::get('/address/{id}/edit', 'App\Http\Controllers\AddressController@edit')->name('address.edit');
    Route::post('/address/{id}/edit', 'App\Http\Controllers\AddressController@editPost')->name('address.edit-post');

    Route::get('/canvass/address/{id}/absent-marked', 'App\Http\Controllers\CanvassController@addressAbsentMarked')->name('canvass.address-absent-marked');
    Route::get('/canvass/address/{id}', 'App\Http\Controllers\CanvassController@address')->name('canvass.address');
    Route::post('/canvass/address/{id}', 'App\Http\Controllers\CanvassController@addressPost')->name('canvass.address-post');
    Route::get('/canvass/print/{id}/absent-marked', 'App\Http\Controllers\CanvassController@printAbsentMarked')->name('canvass.print-absent-marked');
    Route::get('/canvass/print/{id}', 'App\Http\Controllers\CanvassController@print')->name('canvass.print');
    Route::get('/canvass/road/{id}/absent-marked', 'App\Http\Controllers\CanvassController@roadAbsentMarked')->name('canvass.road-absent-marked');
    Route::get('/canvass/road/{id}', 'App\Http\Controllers\CanvassController@road')->name('canvass.road');
    Route::post('/canvass/road/{id}', 'App\Http\Controllers\CanvassController@roadPost')->name('canvass.road-post');

    Route::get('/casework/create/{userID}', 'App\Http\Controllers\CaseworkController@create')->name('casework.create');
    Route::post('/casework/create/{userID}', 'App\Http\Controllers\CaseworkController@createPost')->name('casework.create-post');
    Route::get('/casework/{id}', 'App\Http\Controllers\CaseworkController@show')->name('casework.show');
    Route::post('/casework/{id}', 'App\Http\Controllers\CaseworkController@showPost')->name('casework.show-post');
    Route::get('/casework', 'App\Http\Controllers\CaseworkController@index')->name('casework.index');

    Route::get('/event/create', 'App\Http\Controllers\EventController@create')->name('event.create');
    Route::post('/event/create', 'App\Http\Controllers\EventController@createPost')->name('event.create-post');
    Route::get('/event/{id}/contact/{activistID}', 'App\Http\Controllers\EventController@contact')->name('event.contact');
    Route::post('/event/{id}/contact/{activistID}', 'App\Http\Controllers\EventController@contactPost')->name('event.contact-post');
    Route::post('/event/{id}/contact/{activistID}/not-coming', 'App\Http\Controllers\EventController@contactNotComing')->name('event.contact-not-coming');
    Route::get('/event/{id}/edit', 'App\Http\Controllers\EventController@edit')->name('event.edit');
    Route::post('/event/{id}/edit', 'App\Http\Controllers\EventController@editPost')->name('event.edit-post');
    Route::get('/event/{id}', 'App\Http\Controllers\EventController@show')->name('event.show');
    Route::get('/event', 'App\Http\Controllers\EventController@index')->name('event.index');

    Route::get('/road/{id}', 'App\Http\Controllers\RoadController@show')->name('road.show');

    Route::get('/survey/create', 'App\Http\Controllers\SurveyController@create')->name('survey.create');
    Route::post('/survey/create', 'App\Http\Controllers\SurveyController@createPost')->name('survey.create-post');
    Route::get('/survey/{id}/edit', 'App\Http\Controllers\SurveyController@edit')->name('survey.edit');
    Route::get('/survey/{id}/export', 'App\Http\Controllers\SurveyController@export')->name('survey.export');
    Route::post('/survey/{id}/edit', 'App\Http\Controllers\SurveyController@editPost')->name('survey.edit-post');
    Route::get('/survey/{id}/response', 'App\Http\Controllers\SurveyController@response')->name('survey.response');
    Route::post('/survey/{id}/response', 'App\Http\Controllers\SurveyController@responsePost')->name('survey.response-post');
    Route::get('/survey/{id}/responses', 'App\Http\Controllers\SurveyController@responses')->name('survey.responses');
    Route::get('/survey/{id}', 'App\Http\Controllers\SurveyController@show')->name('survey.show');
    Route::get('/survey', 'App\Http\Controllers\SurveyController@index')->name('survey.index');

    Route::get('/survey-response/{id}', 'App\Http\Controllers\SurveyResponseController@show')->name('survey-response.show');

    Route::get('/user/my-account', 'App\Http\Controllers\UserController@myAccount')->name('user.my-account');
    Route::post('/user/my-account', 'App\Http\Controllers\UserController@myAccountPost')->name('user.my-account-post');

    Route::get('/ward/{id}/export', 'App\Http\Controllers\WardController@export')->name('ward.export');
    Route::get('/ward/{id}', 'App\Http\Controllers\WardController@show')->name('ward.show');
    Route::get('/ward', 'App\Http\Controllers\WardController@index')->name('ward.index');

    Route::group(['middleware' => ['admin']], function ()
    {
        Route::get('/council', 'App\Http\Controllers\CouncilController@index')->name('council.index');
        Route::post('/council', 'App\Http\Controllers\CouncilController@indexPost')->name('council.index-post');

        Route::get('/upload/absent-register', 'App\Http\Controllers\UploadController@absentRegister')->name('upload.absent-register');
        Route::post('/upload/absent-register', 'App\Http\Controllers\UploadController@absentRegisterPost')->name('upload.absent-register-post');
        Route::get('/upload/electoral-register', 'App\Http\Controllers\UploadController@electoralRegister')->name('upload.electoral-register');
        Route::post('/upload/electoral-register', 'App\Http\Controllers\UploadController@electoralRegisterPost')->name('upload.electoral-register-post');
        Route::get('/upload/marked-register', 'App\Http\Controllers\UploadController@markedRegister')->name('upload.marked-register');
        Route::post('/upload/marked-register', 'App\Http\Controllers\UploadController@markedRegisterPost')->name('upload.marked-register-post');
        Route::get('/upload', 'App\Http\Controllers\UploadController@index')->name('upload.index');

        Route::get('/user/create', 'App\Http\Controllers\UserController@create')->name('user.create');
        Route::post('/user/create', 'App\Http\Controllers\UserController@createPost')->name('user.create-post');
        Route::get('/user/{id}/edit', 'App\Http\Controllers\UserController@edit')->name('user.edit');
        Route::post('/user/{id}/edit', 'App\Http\Controllers\UserController@editPost')->name('user.edit-post');
        Route::get('/user', 'App\Http\Controllers\UserController@index')->name('user.index');
    });

    Route::view('/help', 'help')->name('help');
    Route::view('/help/absent-register', 'help.absent-register')->name('help.absent-register');
    Route::view('/help/elector-markers', 'help.elector-markers')->name('help.elector-markers');
    Route::view('/help/electoral-register', 'help.electoral-register')->name('help.electoral-register');
    Route::view('/help/getting-started', 'help.getting-started')->name('help.getting-started');
    Route::view('/help/marked-register', 'help.marked-register')->name('help.marked-register');

    Route::view('/static/elector-markers', 'static.elector-markers')->name('static.elector-markers');
});

app/Models/Activist.php
<?php

namespace App\Models;

use App\Traits\PrimaryKeyUuid;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class Activist extends Model
{
    use HasFactory;
    use LogsActivity;
    use PrimaryKeyUuid;
    use SoftDeletes;

    public $fillable = ['id', 'council_id', 'forename', 'surname', 'email', 'mobile_number', 'phone_number', 'do_not_phone',
        'address', 'city', 'postcode', 'council_ward', 'local_authority', 'constituency',
        'is_member', 'membership_start_date', 'membership_end_date', 'membership_type',
    ];

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults();
    }

    public function contacts(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany('App\Models\Contact');
    }

    public function council(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo('App\Models\Council');
    }

    public function events(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany('App\Models\Event', 'link_activists_events', 'activist_id', 'event_id');
    }

    public static function csvHeaders(): array
    {
        return [
            'Forename',
            'Surname',
            'Email',
            'Mobile Number',
            'Phone Number',
            'Do Not Phone',
            'Address',
            'City',
            'Postcode',
            'Council Ward',
            'Local Authority',
            'Constituency',
            'Is a Member?',
            'Membership Start Date',
            'Membership End Date',
            'Membership Type',
        ];
    }

    public function csvRow(): array
    {
        return [
            $this->forename,
            $this->Surname,
            $this->email,
            $this->mobile_number,
            $this->phone_number,
            $this->do_not_phone,
            $this->address,
            $this->city,
            $this->postcode,
            $this->council_ward,
            $this->local_authority,
            $this->constituency,
            $this->is_a_member,
            $this->membership_start_date,
            $this->membership_end_date,
            $this->membership_type,
        ];
    }

    public static function formatPhoneNumber(string $number): string
    {
        $number       = str_replace(' ', '' , str_replace('+', '', $number));
        $elevenDigits = '';

        switch (strlen($number))
        {
            case 10:
                $elevenDigits = '0'.$number;
                break;

            case 11:
                $elevenDigits = $number;
                break;

            case 12:
                $elevenDigits = '0'.substr($number, 2, 10);
                break;
        }

        switch (substr($elevenDigits, 0, 2))
        {
            case '01':
                if (substr($elevenDigits, 3, 1) === "1")
                {
                    return substr($elevenDigits, 0, 4).' '.substr($elevenDigits, 4, 7);
                } else {
                    return substr($elevenDigits, 0, 5).' '.substr($elevenDigits, 5, 6);
                }
                break;

            case '02':
            case '03':
                return substr($elevenDigits, 0, 3).' '.substr($elevenDigits, 3, 4).' '.substr($elevenDigits, 7, 4);
                break;

            case '07':
                return substr($elevenDigits, 0, 5).' '.substr($elevenDigits, 5, 6);
                break;
        }

        return $elevenDigits;
    }

    public function getFormattedCanPhoneAttribute(): string
    {
        if ($this->do_not_phone)
        {
            return 'N';
        }

        return 'Yes';
    }

    public function getFormattedIsMemberAttribute(): string
    {
        if ($this->is_member)
        {
            return 'Yes';
        }

        return 'N';
    }

    public function getFormattedPhoneAttribute(): string
    {
        $returnArr = [];

        if ($this->phone_number)
        {
            $returnArr[] = 'H: '.$this->phone_number;
        }

        if ($this->mobile_number)
        {
            $returnArr[] = 'M: '.$this->mobile_number;
        }

        return implode('<br />', $returnArr);
    }

    public function getFormattedPhoneAndEmailAttribute(): string
    {
        $returnArr = [];

        if ($this->phone_number)
        {
            $returnArr[] = 'H: '.$this->phone_number;
        }

        if ($this->mobile_number)
        {
            $returnArr[] = 'M: '.$this->mobile_number;
        }

        if ($this->email)
        {
            $returnArr[] = 'E: '.$this->email;
        }

        return implode('<br />', $returnArr);
    }

    public function getNameAttribute(): string
    {
        return $this->forename.' '.$this->surname;
    }

    public static function parseHomeNumber(array $row): string
    {
        $numbers = array_filter([
            $row['can2_phone'],
            $row['Home_Phone'],
            $row['Phone Number'],
        ]);

        foreach ($numbers as $number)
        {
            $formattedNumber = self::formatPhoneNumber($number);

            if (substr($formattedNumber, 1, 1) != "7")
            {
                return $formattedNumber;
            }
        }

        return '';
    }

    public static function parseMobileNumber(array $row): string
    {
        $numbers = array_filter([
            $row['can2_phone'],
            $row['Home_Phone'],
            $row['Phone Number'],
        ]);

        foreach ($numbers as $number)
        {
            $formattedNumber = self::formatPhoneNumber($number);

            if (substr($formattedNumber, 1, 1) == "7")
            {
                return $formattedNumber;
            }
        }

        return '';
    }
}

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class Contact extends Model
{
    use HasFactory;
    use LogsActivity;
    use SoftDeletes;

    public $fillable = ['activist_id', 'event_id', 'user_id', 'date_of_contact', 'enum_contact_type', 'managed_to_contact', 'notes'];

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults();
    }

    public function activist(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo('App\Models\Activist');
    }

    public function event(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo('App\Models\Event');
    }

    public function user(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo('App\Models\User');
    }

    public function getEventNameAttribute(): string
    {
        if ($this->event)
        {
            return $this->event->name;
        }

        return '';
    }

    public function getFormattedManagedToContactAttribute(): string
    {
        if ($this->managed_to_contact)
        {
            return 'Yes';
        }

        return 'N';
    }
}

resources/views/main/activist/index.blade.php
@extends('template')

@section('title')
    All Activists
@endsection

@section('content')
    {{ Form::open(['route' => 'activist.index', 'method' => 'get']) }}

        <div class="card">
            <div class="card-header">Search</div>
            <div class="card-body">
                <div class="row">
                    <div class="col-6">
                        {{ Form::bsText('Forename', 'forename') }}
                        {{ Form::bsText('Surname', 'surname') }}
                        {{ Form::bsSelect('Is a Member', 'is_member', [1 => 'Yes', 0 => 'No'], null, ['placeholder' => '']) }}
                    </div>
                    <div class="col-6">
                        {{ Form::bsText('Council Ward', 'council_ward') }}
                        {{ Form::bsText('Local Authority', 'local_authority') }}
                        {{ Form::bsText('Constituency', 'constituency') }}
                    </div>
                </div>

                {{ Form::bsSubmit('Search Activists') }}
            </div>
        </div>

    {{ Form::close() }}

    <div class="card">
        <div class="card-header">Activists</div>
        <div class="card-body">
            <div class="row row-header">
                <div class="col-2">Name</div>
                <div class="col-3">Contact</div>
                <div class="col-1">Member?</div>
                <div class="col-2">Membership End</div>
                <div class="col-1">Can Phone?</div>
                <div class="col-2">Local Authority</div>
                <div class="col-1">Ward</div>
            </div>

            <div class="row">
                @foreach ($activists as $activist)
                    <div class="col-2"><a href="{{ route('activist.show', $activist->id) }}">{{ $activist->name }}</a></div>
                    <div class="col-3">{!! $activist->formatted_phone_and_email !!}</div>
                    <div class="col-1">{{ $activist->formatted_is_member }}</div>
                    <div class="col-2">{{ $activist->membership_end_date }}</div>
                    <div class="col-1">{{ $activist->formatted_can_phone }}</div>
                    <div class="col-2">{{ $activist->local_authority }}</div>
                    <div class="col-1">{{ $activist->council_ward }}</div>
                @endforeach
            </div>
        </div>
    </div>

    {{ Form::open(['route' => 'activist.upload', 'method' => 'post', 'files' => true]) }}

        <div class="card">
            <div class="card-header">Upload Replacement Activist List</div>
            <div class="card-body">
                {{ Form::bsSelect('Council', 'council_id', $councils->pluck('name', 'id')->toArray()) }}
                {{ Form::bsFile('CSV Upload', 'file') }}
                {{ Form::bsSubmit('Upload new Activists') }}
            </div>
            <div class="card-footer">This requires a direct export in CSV form from Action Network.</div>
        </div>

    {{ Form::close() }}
@endsection

resources/views/main/activist/show.blade.php
@extends('template')

@section('title')
    Activist - {{ $activist->name }}
@endsection

@section('content')
    <p><a href="{{ route('activist.index') }}">Back to all activists</a></p>

    <div class="card">
        <div class="card-header">Activist Details</div>
        <div class="card-body">
            <div class="row">
                <div class="col-2">Name</div>
                <div class="col-10">{{ $activist->name }}</div>

                <div class="col-2">Email</div>
                <div class="col-10">{{ $activist->email }}</div>

                <div class="col-2">Phone</div>
                <div class="col-10">{{ $activist->phone_number }}@if ($activist->do_not_phone) (do not phone)@endif</div>

                <div class="col-2">Mobile</div>
                <div class="col-10">{{ $activist->mobile_number }}@if ($activist->do_not_phone) (do not phone)@endif</div>

                <div class="col-2">Address</div>
                <div class="col-10">{{ $activist->address }}<br />{{ $activist->city }}<br />{{ $activist->postcode }}</div>

                <div class="col-2">Ward</div>
                <div class="col-10">{{ $activist->council_ward }}</div>

                <div class="col-2">Local Authority</div>
                <div class="col-10">{{ $activist->local_authority }}</div>

                <div class="col-2">Constituency</div>
                <div class="col-10">{{ $activist->constituency }}</div>

                <div class="col-2">Membership Details</div>
                <div class="col-10">
                    @if ($activist->membership_type)
                        {{ $activist->membership_type }}

                        @if ($activist->is_member)
                            (Current Member, expiring {{ $activist->membership_end_date }})
                        @else
                            (Former Member, expired {{ $activist->membership_end_date }})
                        @endif
                    @else
                        N/A
                    @endif
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header">Contact History</div>
        <div class="card-body">
            @if (count($activist->contacts))
                <div class="row">
                    <div class="col-2">Date</div>
                    <div class="col-2">Contacted By</div>
                    <div class="col-2">About Event?</div>
                    <div class="col-2">Method</div>
                    <div class="col-4">Notes</div>

                    @foreach ($activist->contacts as $contact)
                        <div class="col-2">{{ $contact->date_of_contact }}</div>
                        <div class="col-2">{{ $contact->user->name }}</div>
                        <div class="col-2">{{ $contact->event_name }}</div>
                        <div class="col-2">
                            {{ $contactTypes[$contact->enum_contact_type] }}

                            @if (!$contact->managed_to_contact)
                                (Unsuccessful)
                            @endif
                        </div>
                        <div class="col-3">{{ $contact->notes }}</div>
                        <div class="col-1">
                            {{ Form::open(['route' => ['activist.contact-delete', $contact->id], 'method' => 'post']) }}
                                {{ Form::hidden('contact_id', $contact->id) }}
                                {{ Form::submit('Delete', ['class' => 'form-control btn btn-danger']) }}
                            {{ Form::close() }}
                        </div>
                    @endforeach
                </div>
            @else
                <p>There is no contact history for this member.</p>
            @endif
        </div>
    </div>

    {{ Form::open(['route' => ['activist.show-post', $activist->id], 'method' => 'post']) }}
    <div class="card">
        <div class="card-header">Record new Contact</div>
        <div class="card-body">
            {{ Form::hidden('managed_to_contact', 0) }}
            {{ Form::hidden('is_attending', 0) }}
            {{ Form::bsDate('Date', 'date_of_contact', date('Y-m-d')) }}
            {{ Form::bsSelect('Method of Contact', 'enum_contact_type', $contactTypes) }}
            {{ Form::bsCheckbox('Successful Contact?', 'managed_to_contact', 1, 1) }}
            {{ Form::bsText('Notes', 'notes') }}
            {{ Form::bsSelect('Specifically about an Event?', 'event_id', $events, null, ['placeholder' => '']) }}
            {{ Form::bsCheckbox('Are they Attending? (if relevant)', 'is_attending', 1) }}
            {{ Form::bsSubmit('Record Attempt to Contact') }}
        </div>
    </div>
@endsection