routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes([
    'register' => false
]);

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth']], function ()
{
    Route::get('/ajax/address-to-voters/{id}', 'App\Http\Controllers\AjaxController@addressToVoters');
    Route::get('/ajax/road-to-addresses/{id}', 'App\Http\Controllers\AjaxController@roadToAddresses');
    Route::get('/ajax/ward-to-roads/{id}', 'App\Http\Controllers\AjaxController@wardToRoads');

    Route::post('/activist/contact-delete', 'App\Http\Controllers\ActivistController@contactDelete')->name('activist.contact-delete');
    Route::post('/activist/upload', 'App\Http\Controllers\ActivistController@upload')->name('activist.upload');
    Route::get('/activist/{id}/export', 'App\Http\Controllers\ActivistController@export')->name('activist.export');
    Route::get('/activist/{id}', 'App\Http\Controllers\ActivistController@show')->name('activist.show');
    Route::post('/activist/{id}', 'App\Http\Controllers\ActivistController@showPost')->name('activist.show-post');
    Route::get('/activist', 'App\Http\Controllers\ActivistController@index')->name('activist.index');

    Route::get('/address/create', 'App\Http\Controllers\AddressController@create')->name('address.create');
    Route::post('/address/create', 'App\Http\Controllers\AddressController@createPost')->name('address.create-post');
    Route::get('/address/{id}/edit', 'App\Http\Controllers\AddressController@edit')->name('address.edit');
    Route::post('/address/{id}/edit', 'App\Http\Controllers\AddressController@editPost')->name('address.edit-post');

    Route::get('/canvass/address/{id}/absent-marked', 'App\Http\Controllers\CanvassController@addressAbsentMarked')->name('canvass.address-absent-marked');
    Route::get('/canvass/address/{id}', 'App\Http\Controllers\CanvassController@address')->name('canvass.address');
    Route::post('/canvass/address/{id}', 'App\Http\Controllers\CanvassController@addressPost')->name('canvass.address-post');
    Route::get('/canvass/print/{id}/absent-marked', 'App\Http\Controllers\CanvassController@printAbsentMarked')->name('canvass.print-absent-marked');
    Route::get('/canvass/print/{id}', 'App\Http\Controllers\CanvassController@print')->name('canvass.print');
    Route::get('/canvass/road/{id}/absent-marked', 'App\Http\Controllers\CanvassController@roadAbsentMarked')->name('canvass.road-absent-marked');
    Route::get('/canvass/road/{id}', 'App\Http\Controllers\CanvassController@road')->name('canvass.road');
    Route::post('/canvass/road/{id}', 'App\Http\Controllers\CanvassController@roadPost')->name('canvass.road-post');

    Route::get('/casework/create/{userID}', 'App\Http\Controllers\CaseworkController@create')->name('casework.create');
    Route::post('/casework/create/{userID}', 'App\Http\Controllers\CaseworkController@createPost')->name('casework.create-post');
    Route::get('/casework/{id}', 'App\Http\Controllers\CaseworkController@show')->name('casework.show');
    Route::post('/casework/{id}', 'App\Http\Controllers\CaseworkController@showPost')->name('casework.show-post');
    Route::get('/casework', 'App\Http\Controllers\CaseworkController@index')->name('casework.index');

    Route::get('/event/create', 'App\Http\Controllers\EventController@create')->name('event.create');
    Route::post('/event/create', 'App\Http\Controllers\EventController@createPost')->name('event.create-post');
    Route::get('/event/{id}/contact/{activistID}', 'App\Http\Controllers\EventController@contact')->name('event.contact');
    Route::post('/event/{id}/contact/{activistID}', 'App\Http\Controllers\EventController@contactPost')->name('event.contact-post');
    Route::post('/event/{id}/contact/{activistID}/not-coming', 'App\Http\Controllers\EventController@contactNotComing')->name('event.contact-not-coming');
    Route::get('/event/{id}/edit', 'App\Http\Controllers\EventController@edit')->name('event.edit');
    Route::post('/event/{id}/edit', 'App\Http\Controllers\EventController@editPost')->name('event.edit-post');
    Route::get('/event/{id}', 'App\Http\Controllers\EventController@show')->name('event.show');
    Route::get('/event', 'App\Http\Controllers\EventController@index')->name('event.index');

    Route::get('/road/{id}', 'App\Http\Controllers\RoadController@show')->name('road.show');

    Route::get('/survey/create', 'App\Http\Controllers\SurveyController@create')->name('survey.create');
    Route::post('/survey/create', 'App\Http\Controllers\SurveyController@createPost')->name('survey.create-post');
    Route::get('/survey/{id}/edit', 'App\Http\Controllers\SurveyController@edit')->name('survey.edit');
    Route::get('/survey/{id}/export', 'App\Http\Controllers\SurveyController@export')->name('survey.export');
    Route::post('/survey/{id}/edit', 'App\Http\Controllers\SurveyController@editPost')->name('survey.edit-post');
    Route::get('/survey/{id}/response', 'App\Http\Controllers\SurveyController@response')->name('survey.response');
    Route::post('/survey/{id}/response', 'App\Http\Controllers\SurveyController@responsePost')->name('survey.response-post');
    Route::get('/survey/{id}/responses', 'App\Http\Controllers\SurveyController@responses')->name('survey.responses');
    Route::get('/survey/{id}', 'App\Http\Controllers\SurveyController@show')->name('survey.show');
    Route::get('/survey', 'App\Http\Controllers\SurveyController@index')->name('survey.index');

    Route::get('/survey-response/{id}', 'App\Http\Controllers\SurveyResponseController@show')->name('survey-response.show');

    Route::get('/user/my-account', 'App\Http\Controllers\UserController@myAccount')->name('user.my-account');
    Route::post('/user/my-account', 'App\Http\Controllers\UserController@myAccountPost')->name('user.my-account-post');

    Route::get('/ward/{id}/export', 'App\Http\Controllers\WardController@export')->name('ward.export');
    Route::get('/ward/{id}', 'App\Http\Controllers\WardController@show')->name('ward.show');
    Route::get('/ward', 'App\Http\Controllers\WardController@index')->name('ward.index');

    Route::group(['middleware' => ['admin']], function ()
    {
        Route::get('/council', 'App\Http\Controllers\CouncilController@index')->name('council.index');
        Route::post('/council', 'App\Http\Controllers\CouncilController@indexPost')->name('council.index-post');

        Route::get('/upload/absent-register', 'App\Http\Controllers\UploadController@absentRegister')->name('upload.absent-register');
        Route::post('/upload/absent-register', 'App\Http\Controllers\UploadController@absentRegisterPost')->name('upload.absent-register-post');
        Route::get('/upload/electoral-register', 'App\Http\Controllers\UploadController@electoralRegister')->name('upload.electoral-register');
        Route::post('/upload/electoral-register', 'App\Http\Controllers\UploadController@electoralRegisterPost')->name('upload.electoral-register-post');
        Route::get('/upload/marked-register', 'App\Http\Controllers\UploadController@markedRegister')->name('upload.marked-register');
        Route::post('/upload/marked-register', 'App\Http\Controllers\UploadController@markedRegisterPost')->name('upload.marked-register-post');
        Route::get('/upload', 'App\Http\Controllers\UploadController@index')->name('upload.index');

        Route::get('/user/create', 'App\Http\Controllers\UserController@create')->name('user.create');
        Route::post('/user/create', 'App\Http\Controllers\UserController@createPost')->name('user.create-post');
        Route::get('/user/{id}/edit', 'App\Http\Controllers\UserController@edit')->name('user.edit');
        Route::post('/user/{id}/edit', 'App\Http\Controllers\UserController@editPost')->name('user.edit-post');
        Route::get('/user', 'App\Http\Controllers\UserController@index')->name('user.index');
    });

    Route::view('/help', 'help')->name('help');
    Route::view('/help/absent-register', 'help.absent-register')->name('help.absent-register');
    Route::view('/help/elector-markers', 'help.elector-markers')->name('help.elector-markers');
    Route::view('/help/electoral-register', 'help.electoral-register')->name('help.electoral-register');
    Route::view('/help/getting-started', 'help.getting-started')->name('help.getting-started');
    Route::view('/help/marked-register', 'help.marked-register')->name('help.marked-register');

    Route::view('/static/elector-markers', 'static.elector-markers')->name('static.elector-markers');
});

app/Models/Road.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class Road extends Model
{
    use HasFactory;
    use LogsActivity;
    use SoftDeletes;

    public $fillable = ['council_id', 'route_id', 'ward_id', 'name'];

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults();
    }

    public function addresses(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany('App\Models\Address');
    }

    public function ward(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo('App\Models\Ward');
    }

    // Returns a string of all delivery routes for addresses in this road.
    public function getDeliveryRouteNamesAttribute(): string
    {
        $routeIDs = \DB::select('SELECT route_id FROM addresses WHERE road_id = '.$this->id.' GROUP BY route_id');
        $array = [];

        foreach ($routeIDs as $object)
        {
            if ($object->route_id > 0)
            {
                $array[] = $object->route_id;
            }
        }

        return implode(', ', Route::whereIn('id', $array)->pluck('name')->toArray());
    }

    public function getNumberOfHousesAttribute(): int
    {
        $countHouses = \DB::select('SELECT count(id) as number_of_houses FROM addresses WHERE road_id = "'.$this->id.'"');

        return $countHouses[0]->number_of_houses;
    }

    public function getNumberOfVotersAttribute(): int
    {
        $addressIDs = $this->addresses->pluck('id')->toArray();
        $countVoters = \DB::select('SELECT count(id) as number_of_voters FROM voters WHERE address_id IN ('.implode(',', $addressIDs).')');

        return $countVoters[0]->number_of_voters;
    }
}

app/Models/Ward.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class Ward extends Model
{
    use HasFactory;
    use LogsActivity;
    use SoftDeletes;

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults();
    }

    public function addresses(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany('App\Models\Address');
    }

    public function council(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo('App\Models\Council');
    }

    public function roads(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany('App\Models\Road');
    }

    public function routes(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany('App\Models\Route');
    }

    public function voters(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany('App\Models\Voter');
    }

    public function canvassNumbersForChart(string $columnName): array
    {
        $canvassData = Voter::whereNotNull($columnName)
            ->groupBy($columnName)
            ->select($columnName, \DB::raw('count(*) as total'))
            ->get()
            ->toArray();

        $jsArray = [];
        foreach ($canvassData as $array)
        {
            $jsArray[$array[$columnName]] = $array['total'];
        }

        return $jsArray;
    }
}

app/Http/Controllers/WardController.php
<?php

namespace App\Http\Controllers;

use App\Enums\GenerallyVotesColor;
use App\Enums\VoteGreenLikelihoodColor;
use App\Models\Address;
use App\Models\Survey;
use App\Models\Voter;
use App\Models\Ward;
use Auth;
use Illuminate\Http\Request;

class WardController extends Controller
{
    public function export(int $id): \Symfony\Component\HttpFoundation\StreamedResponse
    {
        $fileName = 'ward.csv';
        $ward     = Ward::find($id);
        $election = $ward->council->elections()->orderBy('year', 'desc')->first();

        $headers = array(
            "Content-type"        => "text/csv",
            "Content-Disposition" => "attachment; filename=$fileName",
            "Pragma"              => "no-cache",
            "Cache-Control"       => "must-revalidate, post-check=0, pre-check=0",
            "Expires"             => "0"
        );

        $columns = Voter::csvColumns();

        $callback = function () use ($columns, $ward, $election): void {
            $file = fopen('php://output', 'w');

            fputcsv($file, $columns);
            foreach ($ward->voters as $voter) {
                fputcsv($file, $voter->csvRow($election->id));
            }

            fclose($file);
        };

        return response()->stream($callback, 200, $headers);
    }

    public function index(): \Illuminate\View\View
    {
        $args = [];
        $args['wards'] = Ward::whereIn('council_id', Auth::user()->canAccessCouncilIDs())->withCount(['addresses', 'voters'])->with('council')->get();

        return view('main.ward.index', $args);
    }

    public function show(int $id): \Illuminate\View\View
    {
        $args = [];
        $args['ward']   = Ward::find($id);
        $args['roads']  = $args['ward']->roads()->orderBy('name')->get();
        $args['routes'] = $args['ward']->routes()->pluck('name', 'id');
        $args['colorsVotes'] = GenerallyVotesColor::toArray();
        $args['colorsGreen'] = VoteGreenLikelihoodColor::toArray();

        $this->authorize('show', $args['ward']);

        return view('main.ward.show', $args);
    }
}

resources/views/main/ward/index.blade.php
@extends('template')

@section('title')
    All Wards
@endsection

@section('content')
    <div class="card">
        <div class="card-header">Full List of Wards</div>
        <div class="card-body">
            <div class="row row-header">
                <div class="col-3">Council</div>
                <div class="col-3">Ward</div>
                <div class="col-3">Number of Houses / Voters</div>
                <div class="col-3">Delivery Route</div>
            </div>

            @foreach ($wards as $ward)
                <div class="row">
                    <div class="col-3">{{ $ward->council->name }}</div>
                    <div class="col-3"><a href="{{ route('ward.show', $ward->id) }}">{{ $ward->name }}</a></div>
                    <div class="col-3">{{ $ward->addresses_count }} / {{ $ward->voters_count }}</div>
                    <div class="col-3">?</div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

resources/views/main/ward/show.blade.php
@extends('template')

@section('title')
    {{ $ward->name }} Ward
@endsection

@section('content')
    <p><a href="{{ route('ward.export', $ward->id) }}">Export Ward to CSV</a></p>
    <p><a href="{{ route('address.create') }}">Add an Address</a></p>

    <div class="row">
        <div class="col-3">
            <div class="card">
                <div class="card-header">Council Voting Intention</div>
                <div class="card-body"><canvas id="councilVote" width="400" height="400"></canvas></div>
            </div>
        </div>
        <div class="col-3">
            <div class="card">
                <div class="card-header">Council Green Vote Chance</div>
                <div class="card-body"><canvas id="councilGreen" width="400" height="400"></canvas></div>
            </div>
        </div>
        <div class="col-3">
            <div class="card">
                <div class="card-header">Parliament Voting Intention</div>
                <div class="card-body"><canvas id="parlVote" width="400" height="400"></canvas></div>
            </div>
        </div>
        <div class="col-3">
            <div class="card">
                <div class="card-header">Parliament Green Vote Chance</div>
                <div class="card-body"><canvas id="parlGreen" width="400" height="400"></canvas></div>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header">All Roads in this Ward</div>
        <div class="card-body">
            <div class="row row-header">
                <div class="col-4">Road</div>
                <div class="col-1">Houses</div>
                <div class="col-1">Voters</div>
                <div class="col-6">Delivery Route</div>
            </div>

            @foreach ($roads as $road)
                <div class="row">
                    <div class="col-4"><a href="{{ route('road.show', $road->id) }}">{{ $road->name }}</a></div>
                    <div class="col-1">{{ $road->number_of_houses }}</div>
                    <div class="col-1">{{ $road->number_of_voters }}</div>
                    <div class="col-6">{{ $road->delivery_route_names }}</div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

@section('javascript')
    @include('component.chart.js.pie', ['htmlID' => 'councilVote', 'data' => $ward->canvassNumbersForChart('council_enum_generally_votes_latest'), 'colors' => $colorsVotes])
    @include('component.chart.js.pie', ['htmlID' => 'councilGreen', 'data' => $ward->canvassNumbersForChart('council_enum_vote_green_likelihood_latest'), 'colors' => $colorsGreen])
    @include('component.chart.js.pie', ['htmlID' => 'parlVote', 'data' => $ward->canvassNumbersForChart('parl_enum_generally_votes_latest'), 'colors' => $colorsVotes])
    @include('component.chart.js.pie', ['htmlID' => 'parlGreen', 'data' => $ward->canvassNumbersForChart('parl_enum_vote_green_likelihood_latest'), 'colors' => $colorsGreen])
@endsection