routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes([
    'register' => false
]);

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth']], function ()
{
    Route::get('/ajax/address-to-voters/{id}', 'App\Http\Controllers\AjaxController@addressToVoters');
    Route::get('/ajax/road-to-addresses/{id}', 'App\Http\Controllers\AjaxController@roadToAddresses');
    Route::get('/ajax/ward-to-roads/{id}', 'App\Http\Controllers\AjaxController@wardToRoads');

    Route::post('/activist/contact-delete', 'App\Http\Controllers\ActivistController@contactDelete')->name('activist.contact-delete');
    Route::post('/activist/upload', 'App\Http\Controllers\ActivistController@upload')->name('activist.upload');
    Route::get('/activist/{id}/export', 'App\Http\Controllers\ActivistController@export')->name('activist.export');
    Route::get('/activist/{id}', 'App\Http\Controllers\ActivistController@show')->name('activist.show');
    Route::post('/activist/{id}', 'App\Http\Controllers\ActivistController@showPost')->name('activist.show-post');
    Route::get('/activist', 'App\Http\Controllers\ActivistController@index')->name('activist.index');

    Route::get('/address/create', 'App\Http\Controllers\AddressController@create')->name('address.create');
    Route::post('/address/create', 'App\Http\Controllers\AddressController@createPost')->name('address.create-post');
    Route::get('/address/{id}/edit', 'App\Http\Controllers\AddressController@edit')->name('address.edit');
    Route::post('/address/{id}/edit', 'App\Http\Controllers\AddressController@editPost')->name('address.edit-post');

    Route::get('/canvass/address/{id}/absent-marked', 'App\Http\Controllers\CanvassController@addressAbsentMarked')->name('canvass.address-absent-marked');
    Route::get('/canvass/address/{id}', 'App\Http\Controllers\CanvassController@address')->name('canvass.address');
    Route::post('/canvass/address/{id}', 'App\Http\Controllers\CanvassController@addressPost')->name('canvass.address-post');
    Route::get('/canvass/print/{id}/absent-marked', 'App\Http\Controllers\CanvassController@printAbsentMarked')->name('canvass.print-absent-marked');
    Route::get('/canvass/print/{id}', 'App\Http\Controllers\CanvassController@print')->name('canvass.print');
    Route::get('/canvass/road/{id}/absent-marked', 'App\Http\Controllers\CanvassController@roadAbsentMarked')->name('canvass.road-absent-marked');
    Route::get('/canvass/road/{id}', 'App\Http\Controllers\CanvassController@road')->name('canvass.road');
    Route::post('/canvass/road/{id}', 'App\Http\Controllers\CanvassController@roadPost')->name('canvass.road-post');

    Route::get('/casework/create/{userID}', 'App\Http\Controllers\CaseworkController@create')->name('casework.create');
    Route::post('/casework/create/{userID}', 'App\Http\Controllers\CaseworkController@createPost')->name('casework.create-post');
    Route::get('/casework/{id}', 'App\Http\Controllers\CaseworkController@show')->name('casework.show');
    Route::post('/casework/{id}', 'App\Http\Controllers\CaseworkController@showPost')->name('casework.show-post');
    Route::get('/casework', 'App\Http\Controllers\CaseworkController@index')->name('casework.index');

    Route::get('/event/create', 'App\Http\Controllers\EventController@create')->name('event.create');
    Route::post('/event/create', 'App\Http\Controllers\EventController@createPost')->name('event.create-post');
    Route::get('/event/{id}/contact/{activistID}', 'App\Http\Controllers\EventController@contact')->name('event.contact');
    Route::post('/event/{id}/contact/{activistID}', 'App\Http\Controllers\EventController@contactPost')->name('event.contact-post');
    Route::post('/event/{id}/contact/{activistID}/not-coming', 'App\Http\Controllers\EventController@contactNotComing')->name('event.contact-not-coming');
    Route::get('/event/{id}/edit', 'App\Http\Controllers\EventController@edit')->name('event.edit');
    Route::post('/event/{id}/edit', 'App\Http\Controllers\EventController@editPost')->name('event.edit-post');
    Route::get('/event/{id}', 'App\Http\Controllers\EventController@show')->name('event.show');
    Route::get('/event', 'App\Http\Controllers\EventController@index')->name('event.index');

    Route::get('/road/{id}', 'App\Http\Controllers\RoadController@show')->name('road.show');

    Route::get('/survey/create', 'App\Http\Controllers\SurveyController@create')->name('survey.create');
    Route::post('/survey/create', 'App\Http\Controllers\SurveyController@createPost')->name('survey.create-post');
    Route::get('/survey/{id}/edit', 'App\Http\Controllers\SurveyController@edit')->name('survey.edit');
    Route::get('/survey/{id}/export', 'App\Http\Controllers\SurveyController@export')->name('survey.export');
    Route::post('/survey/{id}/edit', 'App\Http\Controllers\SurveyController@editPost')->name('survey.edit-post');
    Route::get('/survey/{id}/response', 'App\Http\Controllers\SurveyController@response')->name('survey.response');
    Route::post('/survey/{id}/response', 'App\Http\Controllers\SurveyController@responsePost')->name('survey.response-post');
    Route::get('/survey/{id}/responses', 'App\Http\Controllers\SurveyController@responses')->name('survey.responses');
    Route::get('/survey/{id}', 'App\Http\Controllers\SurveyController@show')->name('survey.show');
    Route::get('/survey', 'App\Http\Controllers\SurveyController@index')->name('survey.index');

    Route::get('/survey-response/{id}', 'App\Http\Controllers\SurveyResponseController@show')->name('survey-response.show');

    Route::get('/user/my-account', 'App\Http\Controllers\UserController@myAccount')->name('user.my-account');
    Route::post('/user/my-account', 'App\Http\Controllers\UserController@myAccountPost')->name('user.my-account-post');

    Route::get('/ward/{id}/export', 'App\Http\Controllers\WardController@export')->name('ward.export');
    Route::get('/ward/{id}', 'App\Http\Controllers\WardController@show')->name('ward.show');
    Route::get('/ward', 'App\Http\Controllers\WardController@index')->name('ward.index');

    Route::group(['middleware' => ['admin']], function ()
    {
        Route::get('/council', 'App\Http\Controllers\CouncilController@index')->name('council.index');
        Route::post('/council', 'App\Http\Controllers\CouncilController@indexPost')->name('council.index-post');

        Route::get('/upload/absent-register', 'App\Http\Controllers\UploadController@absentRegister')->name('upload.absent-register');
        Route::post('/upload/absent-register', 'App\Http\Controllers\UploadController@absentRegisterPost')->name('upload.absent-register-post');
        Route::get('/upload/electoral-register', 'App\Http\Controllers\UploadController@electoralRegister')->name('upload.electoral-register');
        Route::post('/upload/electoral-register', 'App\Http\Controllers\UploadController@electoralRegisterPost')->name('upload.electoral-register-post');
        Route::get('/upload/marked-register', 'App\Http\Controllers\UploadController@markedRegister')->name('upload.marked-register');
        Route::post('/upload/marked-register', 'App\Http\Controllers\UploadController@markedRegisterPost')->name('upload.marked-register-post');
        Route::get('/upload', 'App\Http\Controllers\UploadController@index')->name('upload.index');

        Route::get('/user/create', 'App\Http\Controllers\UserController@create')->name('user.create');
        Route::post('/user/create', 'App\Http\Controllers\UserController@createPost')->name('user.create-post');
        Route::get('/user/{id}/edit', 'App\Http\Controllers\UserController@edit')->name('user.edit');
        Route::post('/user/{id}/edit', 'App\Http\Controllers\UserController@editPost')->name('user.edit-post');
        Route::get('/user', 'App\Http\Controllers\UserController@index')->name('user.index');
    });

    Route::view('/help', 'help')->name('help');
    Route::view('/help/absent-register', 'help.absent-register')->name('help.absent-register');
    Route::view('/help/elector-markers', 'help.elector-markers')->name('help.elector-markers');
    Route::view('/help/electoral-register', 'help.electoral-register')->name('help.electoral-register');
    Route::view('/help/getting-started', 'help.getting-started')->name('help.getting-started');
    Route::view('/help/marked-register', 'help.marked-register')->name('help.marked-register');

    Route::view('/static/elector-markers', 'static.elector-markers')->name('static.elector-markers');
});

app/Models/Survey/Issue.php
<?php

namespace App\Models\Survey;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class Issue extends Model
{
    use HasFactory;
    use SoftDeletes;

    public $fillable = ['survey_id', 'name'];
    public $table = 'surveys_issues';

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults();
    }

    public function survey(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo('App\Models\Survey');
    }
}

app/Models/Survey/Question.php
<?php

namespace App\Models\Survey;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class Question extends Model
{
    use HasFactory;
    use SoftDeletes;

    public $fillable = ['survey_id', 'name'];
    public $table = 'surveys_questions';

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults();
    }

    public function options(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany('App\Models\Survey\QuestionOption', 'question_id');
    }

    public function survey(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo('App\Models\Survey');
    }
}

app/Models/Survey/QuestionOption.php
<?php

namespace App\Models\Survey;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class QuestionOption extends Model
{
    use HasFactory;
    use SoftDeletes;

    public $fillable = ['question_id', 'name'];
    public $table = 'surveys_questions_options';

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults();
    }
}

app/Models/Survey/Response.php
<?php

namespace App\Models\Survey;

use App\Enums\GenerallyVotes;
use App\Models\Survey\QuestionOption;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class Response extends Model
{
    use HasFactory;
    use SoftDeletes;

    public $fillable = ['address_id', 'survey_id', 'ward_id', 'voter_id', 'date_of_response', 'other_issues',
        'signup_name', 'signup_email', 'signup_phone',
        'volunteer_deliver', 'volunteer_vote', 'volunteer_poster', 'volunteer_other', 'volunteer_text'];
    public $table = 'surveys_responses';

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults();
    }

    public function address(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo('App\Models\Address');
    }

    public function answers(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany('App\Models\Survey\ResponseAnswer');
    }

    public function issues(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany('App\Models\Survey\ResponseIssue');
    }

    public function parties(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany('App\Models\Survey\ResponseParty');
    }

    public function survey(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo('App\Models\Survey');
    }

    public function voter(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo('App\Models\Voter');
    }

    public function ward(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo('App\Models\Ward');
    }

    public function csvRow(): array
    {
        $wardName    = $this->ward->name;
        $addressName = '';
        $voterName   = $this->voter->name ?? '';
        if ($this->address)
        {
            $addressName = $this->address->name.' '.$this->address->road->name;
        }

        $array          = [$this->id, $wardName, $addressName, $voterName];
        $parties        = GenerallyVotes::toArray();
        $convertIssues  = [
            0 => 'Not Important',
            1 => 'Fairly Important',
            2 => 'Very Important',
        ];
        $convertParties = [
            0 => 'Never',
            1 => 'Possibly',
            2 => 'Definitely',
        ];
        $partyResponses = $this->parties()->pluck('answer', 'enum_political_party')->toArray();

        foreach ($this->survey->issues as $issue)
        {
            $array[] = $convertIssues[$this->issues()->where('issue_id', $issue->id)->firstOrNew()->answer] ?? '';
        }

        foreach (array_keys($parties) as $partyKey)
        {
            $key = $partyResponses[$partyKey] ?? '';

            if ($key == '')
            {
                $array[] = '';
            } else {
                $array[]  = $convertParties[$key] ?? '';
            }
        }

        foreach ($this->survey->questions as $question)
        {
            $option   = $this->answers()->where('question_id', $question->id)->first();
            if ($option)
            {
                $optionID = $option->option_id;
                $array[]  = QuestionOption::find($optionID)->name;
            } else {
                $array[]  = '';
            }
        }

        return $array;
    }

    public function getAddressNameAttribute(): string
    {
        if ($this->address)
        {
            return $this->address->name. ' '.$this->address->road->name;
        }

        return '';
    }

    public function getVoterNameAttribute(): string
    {
        if ($this->voter)
        {
            return $this->voter->name;
        }

        return '';
    }

    public function getWardNameAttribute(): string
    {
        if ($this->ward)
        {
            return $this->ward->name;
        }

        return '';
    }

    public function hasSignedUp(): bool
    {
        return $this->signup_email <> '' || $this->signup_phone <> '';
    }

    public function hasVolunteered(): bool
    {
        return $this->volunteer_deliver + $this->volunteer_poster + $this->volunteer_other > 0;
    }

    public function issuesArray(): array
    {
        $return     = [];
        $convertArr = [
            0 => 'Not Interested',
            1 => 'Fairly Interested',
            2 => 'Very Interested',
        ];

        foreach ($this->survey->issues as $issue)
        {
            $answerText = 'N/A';
            $issueResponse = $this->issues()->where('issue_id', $issue->id)->first();
            if ($issueResponse)
            {
                $answerText = $convertArr[$issueResponse->answer];
            }

            $return[$issue->name] = $answerText;
        }

        return $return;
    }

    public function partiesArray(): array
    {
        $return     = [];
        $partyArr   = GenerallyVotes::toArray();
        $convertArr = [
            0 => 'Not Interested',
            1 => 'Fairly Interested',
            2 => 'Very Interested',
        ];

        foreach ($this->parties as $party)
        {
            $return[$partyArr[$party->enum_political_party]] = $convertArr[$party->answer];
        }

        return $return;
    }
}

app/Models/Survey/ResponseAnswer.php
<?php

namespace App\Models\Survey;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class ResponseAnswer extends Model
{
    use HasFactory;
    use SoftDeletes;

    public $fillable = ['question_id', 'response_id', 'option_id', 'additional_text'];
    public $table = 'surveys_responses_answers';

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults();
    }

    public function option(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo('App\Models\Survey\QuestionOption', 'option_id');
    }

    public function question(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo('App\Models\Survey\Question');
    }
}

resources/views/main/survey/create.blade.php
@extends('template')

@section('title')
    Create Survey
@endsection

@section('content')
    {{ Form::open(['route' => 'survey.create-post', 'method' => 'post']) }}

    <div class="card">
        <div class="card-header">New Survey</div>
        <div class="card-body">
            {{ Form::bsText('Name', 'name') }}
            {{ Form::bsSelect('Council', 'council_id', $councils) }}
        </div>
    </div>

    {{ Form::bsSubmit('Create this Survey') }}

    {{ Form::close() }}
@endsection

resources/views/main/survey/edit.blade.php
@extends('template')

@section('title')
    Edit Survey
@endsection

@section('content')
    {{ Form::open(['route' => ['survey.edit-post', $survey->id], 'method' => 'post']) }}

    <div class="card">
        <div class="card-header">Survey Name</div>
        <div class="card-body">
            {{ Form::bsText('Name', 'name', $survey->name) }}
        </div>
    </div>

    @if ($survey->canEdit())
        <div class="card">
            <div class="card-header">How Important are the Following to You?</div>
            <div class="card-body">
                {{ Form::bsTextarea('Add Questions (one per line)', 'add_issues') }}

                @foreach ($survey->issues as $issue)
                    {{ Form::bsCheckbox($issue->name, 'delete_issues[]', $issue->id) }}
                @endforeach
            </div>
            <div class="card-footer">
                You only need to enter a summary of the issue, not the full text as written on the survey itself. The
                software will automatically let you enter whether the issues are not/fairly/very important on a
                subsequent screen.
            </div>
        </div>

        <div class="card">
            <div class="card-header">Current Questions on the Survey</div>
            <div class="card-body">
                @if (!count($survey->questions))
                    <p>No questions have been added to this survey yet</p>
                @else
                    @foreach ($survey->questions as $question)
                        <div class="card">
                            <div class="card-header">{{ $question->name }}</div>
                            <div class="card-body">
                                @foreach ($question->options as $option)
                                    {{ Form::bsCheckboxReverse($option->name, 'delete_options[]', $option->id) }}
                                @endforeach

                                {{ Form::bsText('Add an option to this question', 'add_option_to_question['.$question->id.']') }}
                            </div>
                            <div class="card-footer">
                                {{ Form::bsCheckboxReverse('Delete this Question', 'delete_questions[]', $question->id) }}
                            </div>
                        </div>
                    @endforeach
                @endif
            </div>
        </div>

        <div class="card">
            <div class="card-header">Add Question to Survey "{{ $survey->name }}"</div>
            <div class="card-body">
                {{ Form::bsText('Question', 'new_question_name') }}
                {{ Form::bsTextarea('Options (one per line)', 'new_question_options') }}
            </div>
        </div>
    @endif

    {{ Form::bsSubmit('Update Survey') }}

    {{ Form::close() }}
@endsection

resources/views/main/survey/index.blade.php
@extends('template')

@section('title')
    All Surveys
@endsection

@section('content')
    <p><a href="{{ route('survey.create') }}">Create a new Survey</a></p>

    <div class="card">
        <div class="card-header">Full List of Surveys</div>
        <div class="card-body">
            <div class="row row-header">
                <div class="col-3">Council</div>
                <div class="col-3">Created by User</div>
                <div class="col-3">Name</div>
                <div class="col-3">Number of Responses</div>
            </div>

            @foreach ($surveys as $survey)
                <div class="row">
                    <div class="col-3">{{ $survey->council->name }}</div>
                    <div class="col-3">{{ $survey->user->name }}</div>
                    <div class="col-3">
                        <a href="{{ route('survey.show', $survey->id) }}">{{ $survey->name }}</a>
                        (<a href="{{ route('survey.edit', $survey->id) }}">Edit</a>)
                        (<a href="{{ route('survey.export', $survey->id) }}">Export</a>)
                    </div>
                    <div class="col-3">{{ count($survey->responses) }} <a href="{{ route('survey.responses', $survey->id) }}">View Responses</a>    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

resources/views/main/survey/responses.blade.php
@extends('template')

@section('title')
    All Response to Survey "{{ $survey->name }}"
@endsection

@section('content')
    <div class="card">
        <div class="card-header">Survey Responses</div>
        <div class="card-body">
            <div class="row">
                <div class="col-1">Ward</div>
                <div class="col-2">Address</div>
                <div class="col-2">Voter</div>
                <div class="col-1">Date</div>
                <div class="col-2">Signed Up?</div>
                <div class="col-2">Volunteered?</div>
                <div class="col-2">&nbsp;</div>

                @foreach ($survey->responses as $response)
                    <div class="col-1">{{ $response->ward_name }}</div>
                    <div class="col-2">{{ $response->address_name }}</div>
                    <div class="col-2">{{ $response->voter_name }}</div>
                    <div class="col-1">{{ $response->date_of_response }}</div>
                    <div class="col-2">{{ $response->hasSignedUp() ? 'Yes' : 'No' }}</div>
                    <div class="col-2">{{ $response->hasVolunteered() ? 'Yes' : 'No' }}</div>
                    <div class="col-2"><a href="{{ route('survey-response.show', $response->id) }}">Full Response</a></div>
                @endforeach
            </div>
        </div>
    </div>
@endsection

resources/views/main/survey/show.blade.php
@extends('template')

@section('title')
    Show Survey - {{ $survey->name }}
@endsection

@section('content')
    <p><a href="{{ route('survey.response', $survey->id) }}">Record Response to this Survey</a></p>
    <p><a href="{{ route('survey.export', $survey->id) }}">Export Survey to CSV</a></p>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">Response Summary</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-6"><canvas id="surveysByMonth" width="400" height="400"></canvas></div>
                        <div class="col-6"><canvas id="issuesSummary" width="400" height="400"></canvas></div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12 col-md-5">
            <div class="card">
                <div class="card-header">How Important are the Following to You?</div>
                <div class="card-body">{!! implode('<br />', $survey->issues->pluck('name')->toArray()) !!}</div>
            </div>
        </div>

        <div class="col-12 col-md-7">
            <div class="card">
                <div class="card-header">Questions on the Survey</div>
                <div class="card-body">
                    @if (!count($survey->questions))
                        <p>No questions have been added to this survey yet</p>
                    @else
                        @foreach ($survey->questions as $question)
                            <p>
                                <b>{{ $question->name }}</b>
                                <br />
                                Options: {{ implode(', ', $question->options->pluck('name')->toArray()) }}
                            </p>
                        @endforeach
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

@section('javascript')
@include('component.chart.js.bar', [
    'htmlID' => 'surveysByMonth',
    'title' => 'Number of Responses Filled out by Month',
    'data' => $survey->chartJSItemsByMonth(),
    // 'colors' => $colorsVotes,
])

@include('component.chart.js.bar-stacked', [
    'htmlID' => 'issuesSummary',
    'data' => $survey->chartJSIssues(),
    'labels' => $survey->chartJSIssuesLabels(),
    'title' => 'Responses to main Issues',
    'colors' => [
        'Not Important'    => '#dc3545',
        'Fairly Important' => '#4d4d4d',
        'Very Important'   => '#6AB023',
    ],
])
@endsection